/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminClientsIdRouteImport } from './routes/admin.clients.$id'
import { Route as AdminCertIdRouteImport } from './routes/admin.cert.$id'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminClientsIdRoute = AdminClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertIdRoute = AdminCertIdRouteImport.update({
  id: '/cert/$id',
  path: '/cert/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/verify': typeof VerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/cert/$id': typeof AdminCertIdRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/verify': typeof VerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/cert/$id': typeof AdminCertIdRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/verify': typeof VerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/cert/$id': typeof AdminCertIdRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/verify'
    | '/blog/$slug'
    | '/admin/'
    | '/admin/blog/$id'
    | '/admin/cert/$id'
    | '/admin/clients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/verify'
    | '/blog/$slug'
    | '/admin'
    | '/admin/blog/$id'
    | '/admin/cert/$id'
    | '/admin/clients/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/verify'
    | '/blog/$slug'
    | '/admin/'
    | '/admin/blog/$id'
    | '/admin/cert/$id'
    | '/admin/clients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/clients/$id': {
      id: '/admin/clients/$id'
      path: '/clients/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AdminClientsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cert/$id': {
      id: '/admin/cert/$id'
      path: '/cert/$id'
      fullPath: '/admin/cert/$id'
      preLoaderRoute: typeof AdminCertIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminCertIdRoute: typeof AdminCertIdRoute
  AdminClientsIdRoute: typeof AdminClientsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminCertIdRoute: AdminCertIdRoute,
  AdminClientsIdRoute: AdminClientsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
